### ISSUE TITLE
请问聊天记录保存到哪里？

### ISSUE THREAD

**Issue by shisaq** [lcxfs1991/chat-socket.io#1]
我想问个问题，如果2个在线用户对话产生聊天记录之后，退出登录，再重新登录时，聊天记录从哪里读取呢？必须要用到数据库，还是要保存到local storage，还是socket io就能帮我们保存了？谢谢！

**Comment by lcxfs1991** [comment]
一般都是用数据库的。socket.io不会帮忙存储。

**Comment by shisaq** [comment]
多谢，我打算用local storage试试，毕竟是个简单聊天室， 服务器没必要为用户保留数据

**Comment by lcxfs1991** [comment]
可以的，但注意localstorage的存储限制

**Comment by lackoxygen** [comment]
是先存储到内存 还是直接入库 首次接触这个东西 请教下
